"""Public contract surface for the Guardian Codex Runner preflight bridge."""

from __future__ import annotations

from guardian.codex_runner_bridge.command_bus import (
    build_guardian_bridge_command_specs,
    execute_guardian_bridge_command,
    is_guardian_bridge_command,
)
from guardian.codex_runner_bridge.adapter import (
    GuardianBridgeAdapterError,
    GuardianBridgeCommandError,
    GuardianBridgeJsonError,
    GuardianBridgeUnsupportedOperationError,
    build_codex_runner_command,
    run_codex_runner_json,
)
from guardian.codex_runner_bridge.contracts import (
    ADAPTER_VERSION,
    ALLOWED_GUARDIAN_BRIDGE_OPERATIONS,
    ARCHIVED_CODEXIFY_CORE_ROOT,
    BOUNDARY_LABEL,
    CODEXIFY_ROOT,
    CODEX_RUNNER_ROOT,
    GuardianBridgeAuthority,
    GuardianBridgeEvidencePaths,
    GuardianBridgeOperation,
    GuardianBridgePathError,
    GuardianBridgeRequest,
    GuardianBridgeResponse,
    GuardianBridgeResponseMode,
    GuardianBridgeResult,
    default_authority,
    normalize_bridge_path,
    validate_bridge_request,
    validate_codex_runner_path,
    validate_operation,
    validate_plan_pack_path,
    validate_validation_receipt_path,
)

__all__ = [
    "ADAPTER_VERSION",
    "ALLOWED_GUARDIAN_BRIDGE_OPERATIONS",
    "ARCHIVED_CODEXIFY_CORE_ROOT",
    "BOUNDARY_LABEL",
    "CODEXIFY_ROOT",
    "CODEX_RUNNER_ROOT",
    "GuardianBridgeAuthority",
    "GuardianBridgeAdapterError",
    "GuardianBridgeCommandError",
    "GuardianBridgeEvidencePaths",
    "GuardianBridgeJsonError",
    "GuardianBridgeOperation",
    "GuardianBridgePathError",
    "GuardianBridgeRequest",
    "GuardianBridgeResponse",
    "GuardianBridgeResponseMode",
    "GuardianBridgeResult",
    "GuardianBridgeUnsupportedOperationError",
    "build_codex_runner_command",
    "build_guardian_bridge_command_specs",
    "default_authority",
    "execute_guardian_bridge_command",
    "normalize_bridge_path",
    "is_guardian_bridge_command",
    "run_codex_runner_json",
    "validate_bridge_request",
    "validate_codex_runner_path",
    "validate_operation",
    "validate_plan_pack_path",
    "validate_validation_receipt_path",
]
