from __future__ import annotations

import json
import os
import platform
import secrets
import shutil
from dataclasses import asdict, dataclass
from pathlib import Path


@dataclass(frozen=True)
class DepStatus:
    name: str
    is_present: bool
    found_path: str | None
    help_text: str


@dataclass(frozen=True)
class InstallerBootstrapState:
    setup_complete: bool = False
    runtime_profile: str = "docker"
    allow_cloud_providers: bool = True
    env_path: str = ""
    last_updated_at: str = ""


def _os_hint_lines(dep: str) -> str:
    system_name = platform.system().lower()
    if dep == "docker":
        if "darwin" in system_name:
            return (
                "Install Docker Desktop: "
                "https://www.docker.com/products/docker-desktop/"
            )
        if "windows" in system_name:
            return (
                "Install Docker Desktop (WSL2 recommended): "
                "https://www.docker.com/products/docker-desktop/"
            )
        return "Install Docker Engine: https://docs.docker.com/engine/install/"
    if dep == "ollama":
        return "Install Ollama: https://ollama.com/download"
    return ""


def _resolve_custom_binary_path(custom_path: str | None) -> str | None:
    if not custom_path:
        return None

    candidate = Path(custom_path).expanduser()
    if not candidate.is_absolute():
        candidate = (Path.cwd() / candidate).resolve()
    else:
        candidate = candidate.resolve()

    if candidate.is_file() and os.access(candidate, os.X_OK):
        return str(candidate)
    return None


def detect_dependency(
    binary_name: str,
    display_name: str,
    custom_path: str | None = None,
) -> DepStatus:
    custom_resolved = _resolve_custom_binary_path(custom_path)
    found = custom_resolved or shutil.which(binary_name)
    help_text = _os_hint_lines(binary_name)

    if custom_path and custom_resolved is None:
        help_text = f"Custom path is not executable: {custom_path}. {help_text}"

    return DepStatus(
        name=display_name,
        is_present=found is not None,
        found_path=found,
        help_text=help_text,
    )


def detect_core_dependencies(
    custom_paths: dict[str, str] | None = None,
) -> dict[str, DepStatus]:
    """
    Core deps for a local-first default experience.
    - docker: optional depending on how you run services, but common for DB/redis.
    - ollama: optional unless you want local LLM on first run.
    """

    paths = custom_paths or {}
    return {
        "docker": detect_dependency(
            "docker", "Docker", custom_path=paths.get("docker")
        ),
        "ollama": detect_dependency(
            "ollama", "Ollama", custom_path=paths.get("ollama")
        ),
    }


def env_kv_sanitize(value: str) -> str:
    # Minimal sanitization for .env values.
    if any(ch in value for ch in (" ", "#")):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    return value


def write_env_file(
    env_path: Path,
    kv: dict[str, str],
    *,
    create_backup: bool = True,
) -> None:
    env_path = env_path.expanduser().resolve()
    env_path.parent.mkdir(parents=True, exist_ok=True)

    if env_path.exists() and create_backup:
        backup_path = env_path.with_suffix(env_path.suffix + ".bak")
        backup_path.write_text(
            env_path.read_text(encoding="utf-8"), encoding="utf-8"
        )

    existing_env_values = (
        _read_env_with_order(env_path)[1] if env_path.exists() else {}
    )
    template_path = env_path.parent / ".env.template"
    if template_path.exists():
        base_order, base_values = _read_env_with_order(template_path)
    elif env_path.exists():
        base_order, base_values = _read_env_with_order(env_path)
    else:
        base_order, base_values = ([], {})

    merged_values = dict(base_values)
    for key, value in kv.items():
        if value is None:
            continue
        merged_values[key] = value

    guardian_api_key = _choose_guardian_api_key(
        existing_env_value=existing_env_values.get("GUARDIAN_API_KEY", ""),
        seed_value=base_values.get("GUARDIAN_API_KEY", ""),
        kv_value=kv.get("GUARDIAN_API_KEY", ""),
    )
    merged_values["GUARDIAN_API_KEY"] = guardian_api_key
    merged_values["VITE_GUARDIAN_API_KEY"] = guardian_api_key

    lines = []
    lines.append("# Generated by Codexify Setup Wizard")
    lines.append(
        "# Safe to edit. Re-running the wizard will overwrite this file "
        "(and create a .bak)."
    )

    written: set[str] = set()
    for key in base_order:
        if key in merged_values and key not in written:
            lines.append(f"{key}={env_kv_sanitize(merged_values[key])}")
            written.add(key)

    for key in kv:
        if key in merged_values and key not in written:
            lines.append(f"{key}={env_kv_sanitize(merged_values[key])}")
            written.add(key)

    for key, value in merged_values.items():
        if key in written:
            continue
        lines.append(f"{key}={env_kv_sanitize(value)}")

    lines.append("")
    env_path.write_text("\n".join(lines), encoding="utf-8")


def default_env_target(repo_root: Path) -> Path:
    """
    Prefer .env.local if you want to keep developer overrides separate.
    If your repo already uses .env, switch to that for consistency.
    """

    return repo_root / ".env"


def default_installer_state_path(repo_root: Path) -> Path:
    return repo_root / ".codexify" / "installer-bootstrap-state.json"


def default_installer_bootstrap_state(
    repo_root: Path,
) -> InstallerBootstrapState:
    return InstallerBootstrapState(env_path=str(default_env_target(repo_root)))


def _coerce_bool(value: object, default: bool) -> bool:
    if isinstance(value, bool):
        return value
    if isinstance(value, str):
        normalized = value.strip().lower()
        if normalized in {"1", "true", "yes", "y", "on"}:
            return True
        if normalized in {"0", "false", "no", "n", "off"}:
            return False
    return default


def write_installer_state_file(
    state_path: Path,
    state: InstallerBootstrapState,
) -> None:
    resolved = state_path.expanduser().resolve()
    resolved.parent.mkdir(parents=True, exist_ok=True)
    resolved.write_text(
        json.dumps(asdict(state), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def read_installer_state_file(repo_root: Path) -> InstallerBootstrapState:
    state_path = default_installer_state_path(repo_root).expanduser().resolve()
    default_state = default_installer_bootstrap_state(repo_root)

    try:
        raw_state = json.loads(state_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError, TypeError, ValueError):
        return default_state

    if not isinstance(raw_state, dict):
        return default_state

    runtime_profile = str(
        raw_state.get("runtime_profile") or default_state.runtime_profile
    )
    if runtime_profile not in {"docker", "external"}:
        runtime_profile = default_state.runtime_profile

    env_path = str(raw_state.get("env_path") or default_state.env_path)
    last_updated_at = str(
        raw_state.get("last_updated_at") or default_state.last_updated_at
    )

    return InstallerBootstrapState(
        setup_complete=_coerce_bool(
            raw_state.get("setup_complete"), default_state.setup_complete
        ),
        runtime_profile=runtime_profile,
        allow_cloud_providers=_coerce_bool(
            raw_state.get("allow_cloud_providers"),
            default_state.allow_cloud_providers,
        ),
        env_path=env_path,
        last_updated_at=last_updated_at,
    )


def read_env_file(env_path: Path) -> dict[str, str]:
    """
    Minimal .env parser:
    - supports KEY=VALUE
    - ignores blank lines and comments (# ...)
    - strips surrounding quotes
    """
    resolved = env_path.expanduser().resolve()
    if not resolved.exists():
        return {}

    output: dict[str, str] = {}
    for raw in resolved.read_text(encoding="utf-8").splitlines():
        parsed = _parse_env_line(raw)
        if parsed is None:
            continue
        key, value = parsed
        output[key] = value
    return output


def _parse_env_line(raw: str) -> tuple[str, str] | None:
    line = raw.strip()
    if not line or line.startswith("#") or "=" not in line:
        return None

    key, value = line.split("=", 1)
    key = key.strip()
    value = value.strip()
    if len(value) >= 2 and (
        (value[0] == value[-1] == '"') or (value[0] == value[-1] == "'")
    ):
        value = value[1:-1]
    return key, value


def _read_env_with_order(env_path: Path) -> tuple[list[str], dict[str, str]]:
    order: list[str] = []
    values: dict[str, str] = {}
    for raw in env_path.read_text(encoding="utf-8").splitlines():
        parsed = _parse_env_line(raw)
        if parsed is None:
            continue
        key, value = parsed
        order.append(key)
        values[key] = value
    return order, values


def _is_placeholder_guardian_api_key(value: str) -> bool:
    lowered = value.strip().lower()
    if not lowered:
        return True
    return lowered in {
        "dev-local-only-change-me",
        "change-me",
        "changeme",
        "replace-me",
        "replace-with-real-key",
        "example",
        "example-key",
    }


def _choose_guardian_api_key(
    *,
    existing_env_value: str,
    seed_value: str,
    kv_value: str | None,
) -> str:
    existing = existing_env_value.strip()
    if existing and not _is_placeholder_guardian_api_key(existing):
        return existing

    provided = (kv_value or "").strip()
    if provided:
        return provided

    seeded = seed_value.strip()
    if seeded and not _is_placeholder_guardian_api_key(seeded):
        return seeded

    return secrets.token_hex(32)


@dataclass(frozen=True)
class DoctorItem:
    name: str
    ok: bool
    required: bool
    detail: str = ""


def _truthy(value: str | None) -> bool:
    if value is None:
        return False
    return value.strip().lower() in {"1", "true", "yes", "y", "on"}


def _notion_target_mode(env: dict[str, str]) -> str:
    mode = (env.get("NOTION_TARGET_MODE") or "").strip().lower()
    return mode or "database"


def _has_any(env: dict[str, str], keys: list[str]) -> bool:
    return any(env.get(key, "").strip() for key in keys)


def build_doctor_report(repo_root: Path) -> tuple[list[DoctorItem], int]:
    """
    Returns (items, exit_code).
    exit_code is 0 if all REQUIRED items are ok, else 1.
    """
    root = repo_root.resolve()
    env_path = default_env_target(root)
    env = read_env_file(env_path)

    deps = detect_core_dependencies()

    allow_cloud = _truthy(env.get("ALLOW_CLOUD_PROVIDERS", "true"))
    ollama_required = not allow_cloud

    # Docker requiredness: enforce only if existing config explicitly implies it.
    docker_required = False
    if "DATABASE_URL" in env and not env.get("DATABASE_URL", "").strip():
        docker_required = True
    if "ENABLE_OUTBOX" in env and _truthy(env.get("ENABLE_OUTBOX")):
        docker_required = True

    items: list[DoctorItem] = []
    items.append(
        DoctorItem(
            name=".env present",
            ok=env_path.exists(),
            required=True,
            detail=str(env_path),
        )
    )

    docker = deps["docker"]
    items.append(
        DoctorItem(
            name="Docker available",
            ok=docker.is_present,
            required=docker_required,
            detail=docker.found_path or docker.help_text,
        )
    )

    ollama = deps["ollama"]
    items.append(
        DoctorItem(
            name="Ollama available",
            ok=ollama.is_present,
            required=ollama_required,
            detail=ollama.found_path or ollama.help_text,
        )
    )

    def req_if_enabled(
        flag_key: str, secret_key: str, label: str
    ) -> DoctorItem:
        enabled = _truthy(env.get(flag_key, "false"))
        secret = env.get(secret_key, "").strip()
        ok = (not enabled) or bool(secret)
        detail = "enabled" if enabled else "disabled"
        if enabled and not secret:
            detail = f"enabled but {secret_key} missing"
        return DoctorItem(name=label, ok=ok, required=enabled, detail=detail)

    def notion_connector_item() -> DoctorItem:
        enabled = _truthy(env.get("CONNECTOR_NOTION_ENABLED", "false"))
        if not enabled:
            return DoctorItem(
                name="Notion connector config",
                ok=True,
                required=False,
                detail="disabled",
            )

        notion_api_key = env.get("NOTION_API_KEY", "").strip()
        if not notion_api_key:
            return DoctorItem(
                name="Notion connector config",
                ok=False,
                required=True,
                detail="enabled but NOTION_API_KEY missing",
            )

        mode = _notion_target_mode(env)
        if mode == "database":
            if not _has_any(env, ["NOTION_DATABASES", "NOTION_DATABASE_ID"]):
                return DoctorItem(
                    name="Notion connector config",
                    ok=False,
                    required=True,
                    detail=(
                        "enabled mode=database but missing "
                        "NOTION_DATABASES/NOTION_DATABASE_ID"
                    ),
                )
            return DoctorItem(
                name="Notion connector config",
                ok=True,
                required=True,
                detail="enabled mode=database",
            )

        if mode == "page":
            notion_parent_page_id = env.get("NOTION_PARENT_PAGE_ID", "").strip()
            if not notion_parent_page_id:
                return DoctorItem(
                    name="Notion connector config",
                    ok=False,
                    required=True,
                    detail="enabled mode=page but NOTION_PARENT_PAGE_ID missing",
                )
            return DoctorItem(
                name="Notion connector config",
                ok=True,
                required=True,
                detail="enabled mode=page",
            )

        return DoctorItem(
            name="Notion connector config",
            ok=False,
            required=True,
            detail=f"enabled but invalid NOTION_TARGET_MODE={mode!r}",
        )

    items.append(notion_connector_item())
    items.append(
        req_if_enabled(
            "CONNECTOR_GITHUB_ENABLED",
            "GITHUB_TOKEN",
            "GitHub connector config",
        )
    )

    exit_code = 0
    for item in items:
        if item.required and not item.ok:
            exit_code = 1
            break

    return items, exit_code
