from __future__ import annotations

import os
import platform
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Optional


@dataclass(frozen=True)
class DepStatus:
    name: str
    is_present: bool
    found_path: str | None
    help_text: str


def _os_hint_lines(dep: str) -> str:
    system_name = platform.system().lower()
    if dep == "docker":
        if "darwin" in system_name:
            return (
                "Install Docker Desktop: "
                "https://www.docker.com/products/docker-desktop/"
            )
        if "windows" in system_name:
            return (
                "Install Docker Desktop (WSL2 recommended): "
                "https://www.docker.com/products/docker-desktop/"
            )
        return "Install Docker Engine: https://docs.docker.com/engine/install/"
    if dep == "ollama":
        return "Install Ollama: https://ollama.com/download"
    return ""


def _resolve_custom_binary_path(custom_path: str | None) -> str | None:
    if not custom_path:
        return None

    candidate = Path(custom_path).expanduser()
    if not candidate.is_absolute():
        candidate = (Path.cwd() / candidate).resolve()
    else:
        candidate = candidate.resolve()

    if candidate.is_file() and os.access(candidate, os.X_OK):
        return str(candidate)
    return None


def detect_dependency(
    binary_name: str,
    display_name: str,
    custom_path: str | None = None,
) -> DepStatus:
    custom_resolved = _resolve_custom_binary_path(custom_path)
    found = custom_resolved or shutil.which(binary_name)
    help_text = _os_hint_lines(binary_name)

    if custom_path and custom_resolved is None:
        help_text = f"Custom path is not executable: {custom_path}. {help_text}"

    return DepStatus(
        name=display_name,
        is_present=found is not None,
        found_path=found,
        help_text=help_text,
    )


def detect_core_dependencies(
    custom_paths: dict[str, str] | None = None,
) -> dict[str, DepStatus]:
    """
    Core deps for a local-first default experience.
    - docker: optional depending on how you run services, but common for DB/redis.
    - ollama: optional unless you want local LLM on first run.
    """

    paths = custom_paths or {}
    return {
        "docker": detect_dependency(
            "docker", "Docker", custom_path=paths.get("docker")
        ),
        "ollama": detect_dependency(
            "ollama", "Ollama", custom_path=paths.get("ollama")
        ),
    }


def env_kv_sanitize(value: str) -> str:
    # Minimal sanitization for .env values.
    if any(ch in value for ch in (" ", "#")):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    return value


def write_env_file(
    env_path: Path,
    kv: dict[str, str],
    *,
    create_backup: bool = True,
) -> None:
    env_path = env_path.expanduser().resolve()
    env_path.parent.mkdir(parents=True, exist_ok=True)

    if env_path.exists() and create_backup:
        backup_path = env_path.with_suffix(env_path.suffix + ".bak")
        backup_path.write_text(
            env_path.read_text(encoding="utf-8"), encoding="utf-8"
        )

    lines = []
    lines.append("# Generated by Codexify Setup Wizard")
    lines.append(
        "# Safe to edit. Re-running the wizard will overwrite this file "
        "(and create a .bak)."
    )
    for key, value in kv.items():
        if value is None:
            continue
        lines.append(f"{key}={env_kv_sanitize(value)}")
    lines.append("")
    env_path.write_text("\n".join(lines), encoding="utf-8")


def default_env_target(repo_root: Path) -> Path:
    """
    Prefer .env.local if you want to keep developer overrides separate.
    If your repo already uses .env, switch to that for consistency.
    """

    return repo_root / ".env"
