from __future__ import annotations

from pathlib import Path
from shutil import copy2
from typing import Mapping


def render_env_from_template(
    template_path: Path, overrides: dict[str, str]
) -> str:
    """
    Render .env text by overlaying key/value overrides onto a template file.

    Rules:
    - preserve comments and blank lines from template
    - replace values for keys that already exist in template assignments
    - append unknown override keys under a generated header
    """
    text = template_path.read_text(encoding="utf-8")
    lines = text.splitlines()

    rendered: list[str] = []
    seen: set[str] = set()

    for line in lines:
        stripped = line.lstrip()
        if not stripped or stripped.startswith("#"):
            rendered.append(line)
            continue

        equals_at = line.find("=")
        if equals_at < 0:
            rendered.append(line)
            continue

        key_part = line[:equals_at]
        key = key_part.strip()
        if key.startswith("export "):
            key = key[len("export ") :].strip()

        if not key or key not in overrides:
            rendered.append(line)
            continue

        seen.add(key)
        rendered.append(f"{line[: equals_at + 1]}{overrides[key]}")

    missing_keys = [k for k in overrides if k not in seen]
    if missing_keys:
        if rendered and rendered[-1] != "":
            rendered.append("")
        rendered.append("# Generated by Codexify Setup Wizard")
        for key in missing_keys:
            rendered.append(f"{key}={overrides[key]}")

    return "\n".join(rendered) + "\n"


def _render_env_from_kv(kv: Mapping[str, str]) -> str:
    lines = [f"{key}={value}" for key, value in kv.items()]
    return ("\n".join(lines) + "\n") if lines else ""


def write_env_file(
    env_path: Path, kv: dict[str, str], repo_root: Path | None = None
) -> Path:
    """
    Write .env with backup support.

    If ``repo_root/.env.template`` exists, seed from the template and overlay
    ``kv`` values. Otherwise fallback to sparse key/value rendering.
    """
    env_path = Path(env_path)
    root = Path(repo_root) if repo_root is not None else env_path.parent
    template_path = root / ".env.template"

    if template_path.exists():
        content = render_env_from_template(template_path, kv)
    else:
        content = _render_env_from_kv(kv)

    if env_path.exists():
        backup_path = env_path.with_name(f"{env_path.name}.bak")
        copy2(env_path, backup_path)

    env_path.write_text(content, encoding="utf-8")
    return env_path
