use crate::vault::Vault;
use crate::biometric;
use crate::linking;
use once_cell::sync::Lazy;
use std::collections::HashMap;
use std::sync::Mutex;
use uuid::Uuid;
use tauri::command;

/// In‑memory map of session tokens to a placeholder value.
/// In a real implementation this would map to a per‑window
/// cryptographic context. For now we only generate a
/// UUID token that the frontend can store.
static SESSION_TOKENS: Lazy<Mutex<HashMap<String, ()>>> = Lazy::new(|| Mutex::new(HashMap::new()));

/// Generate a new session token and ensure a device key exists.
#[command]
pub async fn get_vault_key() -> Result<String, String> {
    // Ensure a device key exists; if not, generate one.
    if Vault::get_key().is_err() {
        // Generate a random 32‑byte key and store it.
        let mut rng = rand::thread_rng();
        let mut key = [0u8; 32];
        rand::RngCore::fill_bytes(&mut rng, &mut key);
        Vault::store_key(&key)?;
    }

    // Generate a UUID token for the session.
    let token = Uuid::new_v4().to_string();
    SESSION_TOKENS
        .lock()
        .unwrap()
        .insert(token.clone(), ());
    Ok(token)
}

/// Encrypt data using the device key stored in the OS keyring.
/// Returns `nonce || ciphertext || tag` as a single byte vector.
#[command]
pub async fn encrypt_vault(data: Vec<u8>) -> Result<Vec<u8>, String> {
    Vault::encrypt(&data)
}

/// Decrypt data that was encrypted with `encrypt_vault`.
#[command]
pub async fn decrypt_vault(data: Vec<u8>) -> Result<Vec<u8>, String> {
    Vault::decrypt(&data)
}

/// Perform biometric authentication.
/// Returns `true` on success, `false` otherwise.
#[command]
pub async fn biometric_auth() -> Result<bool, String> {
    biometric::authenticate()
}

/// Initiate the device linking flow.
/// The `payload` is a JSON string containing the QR‑code
/// or short‑code generated by the desktop side.
#[command]
pub async fn link_device(payload: String) -> Result<(), String> {
    linking::handle_link(payload)
}

/// Export the encrypted vault file as a byte vector.
/// The data remains encrypted.
#[command]
pub async fn export_vault() -> Result<Vec<u8>, String> {
    Vault::export()
}

/// Import an encrypted vault file.
/// The provided data replaces the existing
/// encrypted vault after securely shredding
/// the previous file.
#[command]
pub async fn import_vault(data: Vec<u8>) -> Result<(), String> {
    Vault::import(&data)
}

/// Securely shred the vault file and delete the stored key.
#[command]
pub async fn shred_vault() -> Result<(), String> {
    Vault::shred()
}
