# Generated from contracts/bootstrap/readiness.v1.json. Do not edit.
BOOTSTRAP_CONTRACT_VERSION=1
BootstrapWorkflow_INSPECTING=inspecting
BootstrapWorkflow_CONFIGURING=configuring
BootstrapWorkflow_DOWNLOADING=downloading
BootstrapWorkflow_STARTING=starting
BootstrapWorkflow_MIGRATING=migrating
BootstrapWorkflow_VERIFYING=verifying
BootstrapWorkflow_PAUSED=paused
BootstrapWorkflow_ACTION_REQUIRED=action_required
BootstrapWorkflow_FAILED=failed
BootstrapWorkflow_COMPLETE=complete
BootstrapHumanAction_NONE=none
BootstrapHumanAction_CONSENT_REQUIRED=consent_required
BootstrapHumanAction_CREDENTIALS_REQUIRED=credentials_required
BootstrapHumanAction_PROVIDER_MODEL_CHOICE_REQUIRED=provider_model_choice_required
BootstrapHumanAction_NETWORK_UNAVAILABLE=network_unavailable
BootstrapHumanAction_PREREQUISITE_UNAVAILABLE=prerequisite_unavailable
